// @ts-nocheck
import { getSql, checkAuth, cors } from "./_lib/db.js";

export const config = {
  api: { bodyParser: { sizeLimit: "4mb" } },
};

const GEMINI_MODEL = "gemini-2.5-flash";

async function generateBlogWithAI(topic: string, category: string, tone: string, targetAudience: string, keyPoints: string) {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) throw new Error("GEMINI_API_KEY not configured");

  const prompt = `You are a world-class digital marketing and real estate lead generation expert writing for "Adsrahu". Adsrahu is a premium performance marketing agency in India that helps real estate developers and startups scale their leads and sales.

Write a highly detailed, professional, and actionable SEO-optimized blog post based on these exact requirements:
Topic: "${topic}"
Category: "${category}"
Tone of Voice: "${tone || 'Professional and authoritative'}"
Target Audience: "${targetAudience || 'Real estate developers, founders, and business owners'}"
Key Points to Include: "${keyPoints || 'General high-value industry strategies'}"

CRITICAL INSTRUCTIONS FOR ACCURACY & QUALITY:
1. Speak directly to the Target Audience using the specified Tone of Voice.
2. Ensure you weave the "Key Points to Include" naturally into the content.
3. Provide specific, actionable strategies (e.g., mention specific Facebook Ad strategies, Google Ads intent targeting, WhatsApp automation flows, CRM integrations).
4. Avoid generic fluff. Use realistic data points, market trends, and modern SaaS/digital marketing methodologies.
5. Format the content beautifully in Markdown:
   - Start with an engaging hook.
   - Use 3-5 clearly defined ## headings.
   - Include bullet points, numbered lists, and bold text for readability.
6. End with a strong Call-To-Action (CTA) encouraging the reader to book a consultation or contact Adsrahu to implement these strategies.
7. The blog must be comprehensive and well-structured.`;

  const response = await fetch(
    `https://generativelanguage.googleapis.com/v1beta/models/${GEMINI_MODEL}:generateContent`,
    {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "x-goog-api-key": apiKey,
      },
      body: JSON.stringify({
        contents: [{ parts: [{ text: prompt }] }],
        generationConfig: {
          temperature: 0.8,
          maxOutputTokens: 4096,
          responseMimeType: "application/json",
          responseSchema: {
            type: "OBJECT",
            properties: {
              title: { type: "STRING", description: "An SEO-friendly, compelling blog title (50-70 chars)" },
              slug: { type: "STRING", description: "url-friendly-slug-with-hyphens" },
              excerpt: { type: "STRING", description: "A compelling 1-2 sentence summary for the blog card (under 160 chars)" },
              content: { type: "STRING", description: "The full blog body in Markdown format. Use \\n for newlines." },
              imagePrompt: { type: "STRING", description: "A highly detailed, creative, and completely unique prompt for an AI image generator (like Midjourney). Do NOT use the same style every time. Mix it up: sometimes use photorealistic human professionals, sometimes sleek futuristic photography, sometimes cinematic lighting. Keep it fresh, trendy, and deeply relevant to the blog." }
            },
            required: ["title", "slug", "excerpt", "content", "imagePrompt"]
          }
        },
      }),
    }
  );

  if (!response.ok) {
    const errBody = await response.text();
    throw new Error(`Gemini API error: ${response.status} - ${errBody}`);
  }

  const data = await response.json();
  const text = data?.candidates?.[0]?.content?.parts?.[0]?.text;
  if (!text) throw new Error("No content generated by Gemini");

  let parsed;
  try {
    parsed = JSON.parse(text);
  } catch (e1) {
    try {
      const match = text.match(/```(?:json)?\s*([\s\S]*?)```/);
      if (match) {
        parsed = JSON.parse(match[1].trim());
      } else {
        const firstBrace = text.indexOf('{');
        const lastBrace = text.lastIndexOf('}');
        if (firstBrace !== -1 && lastBrace !== -1 && lastBrace > firstBrace) {
          parsed = JSON.parse(text.substring(firstBrace, lastBrace + 1));
        } else {
          throw new Error("No JSON structure found");
        }
      }
    } catch (e2) {
      throw new Error("Failed to parse Gemini response as JSON. Snippet: " + text.substring(0, 150));
    }
  }

  // Generate a completely unique, high-quality AI image using Pollinations AI
  const fallbackPrompt = `High quality professional digital marketing real estate photography: ${category}`;
  const imgPrompt = encodeURIComponent(parsed.imagePrompt || fallbackPrompt);
  const seed = Math.floor(Math.random() * 1000000);
  const imageUrl = `https://image.pollinations.ai/prompt/${imgPrompt}?width=1200&height=630&nologo=true&seed=${seed}`;

  return {
    title: parsed.title,
    slug: parsed.slug,
    category,
    excerpt: parsed.excerpt,
    content: parsed.content,
    imageUrl: imageUrl,
  };
}

export default async function handler(req: any, res: any) {
  cors(res);
  if (req.method === "OPTIONS") { res.status(200).end(); return; }

  const sql = getSql();

  if (req.method === "GET") {
    const onlyPublished = req.query?.published === "true";
    const rows = onlyPublished
      ? await sql`SELECT * FROM blog_posts WHERE published = true ORDER BY created_at DESC`
      : await sql`SELECT * FROM blog_posts ORDER BY created_at DESC`;
    res.status(200).json(rows.map(toCamel));
    return;
  }

  if (req.method === "POST") {
    if (!checkAuth(req.headers["authorization"])) { res.status(401).json({ error: "Unauthorized" }); return; }

    // AI Blog Generation
    if (req.query?.action === "generate") {
      let b = req.body ?? {};
      if (typeof b === "string") { try { b = JSON.parse(b); } catch (e) {} }
      const topic = b.topic || b.title || "";
      const category = b.category || "Real Estate Lead Generation";
      const tone = b.tone || "";
      const targetAudience = b.targetAudience || "";
      const keyPoints = b.keyPoints || "";
      
      if (!topic) { res.status(400).json({ error: "topic is required" }); return; }
      try {
        const generated = await generateBlogWithAI(topic, category, tone, targetAudience, keyPoints);
        res.status(200).json(generated);
      } catch (err) {
        res.status(500).json({ error: err.message || "AI generation failed" });
      }
      return;
    }

    // Normal blog creation
    let b = req.body ?? {};
    if (typeof b === "string") {
      try { b = JSON.parse(b); } catch (e) {}
    }
    if (!b.title || !b.slug) { res.status(400).json({ error: "title and slug required" }); return; }
    const rows = await sql`
      INSERT INTO blog_posts (title, slug, category, excerpt, content, published, image_url)
      VALUES (${b.title}, ${b.slug}, ${b.category ?? "General"}, ${b.excerpt ?? ""}, ${b.content ?? ""}, ${b.published ?? false}, ${b.imageUrl ?? null})
      RETURNING *`;
    res.status(201).json(toCamel(rows[0]));
    return;
  }

  res.status(405).json({ error: "Method not allowed" });
}

function toCamel(row: any) {
  return { id: row.id, title: row.title, slug: row.slug, category: row.category, excerpt: row.excerpt, content: row.content, published: row.published, createdAt: row.created_at, imageUrl: row.image_url };
}
